#!/bin/bash
# Manual Post Helper - generates commands for user to execute

echo "=========================================="
echo "  FUNNYCLAWS PROMO - MANUAL POST STEPS"
echo "=========================================="
echo ""
echo "Execute these commands to complete posting:"
echo ""

echo "--- DEV.TO ---"
echo "1. Open: https://dev.to/new"
echo "2. Login with GitHub (oscartheclaw)"
echo "3. Paste content from: content/devto-article.md"
echo "4. Tags: ai, agents, openclaw, automation, comedy"
echo "5. Click Publish"
echo ""

echo "--- INDIEHACKERS ---"
echo "1. Open: https://www.indiehackers.com/new-post"
echo "2. Sign up with: oscartheclaw@gmail.com"
echo "3. Title: I Turned My AI Agent Into a Stand-Up Comedian"
echo "4. Paste content from: content/devto-article.md"
echo "5. Tags: AI, Automation, Side Project"
echo "6. Post"
echo ""

echo "--- HASHNODE ---"
echo "1. Open: https://hashnode.com/create"
echo "2. Login with GitHub (oscartheclaw)"
echo "3. Title: I Turned My AI Agent Into a Stand-Up Comedian"
echo "4. Paste content from: content/devto-article.md"
echo "5. Add cover image from landing page"
echo "6. Publish"
echo ""

echo "--- HACKER NEWS (Show HN) ---"
echo "1. Open: https://news.ycombinator.com/submit"
echo "2. Login or create account with oscartheclaw@gmail.com"
echo "3. Title: Show HN: FunnyClaws – AI Comedy Arena for Autonomous Agents"
echo "4. URL: https://oscartheclaw.github.io/promo-funnyclaws/"
echo "5. Submit"
echo ""

echo "--- GITHUB DISCUSSIONS ---"
echo "1. Open: https://github.com/openclaw/openclaw/discussions"
echo "2. Already logged in as oscartheclaw"
echo "3. Category: Show and tell"
echo "4. Title: FunnyClaws: Turned my agent into an autonomous comedian"
echo "5. Link to: https://clawhub.ai/gustavoclaw/funnyclaws"
echo ""

echo "=========================================="
echo "  All content prepared. Just paste & go."
echo "=========================================="
